# Generated by Django 3.1.1 on 2021-03-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Course_Description',
            field=models.CharField(default='Working', max_length=255),
        ),
    ]
