# Generated by Django 3.1.1 on 2021-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoapp', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='exams',
            fields=[
                ('Exam_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Exam_Description', models.CharField(default='Working', max_length=255)),
                ('Exam_fees', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Exam Details',
            },
        ),
    ]
