# Generated by Django 3.1.1 on 2021-05-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clginfoapp', '0007_auto_20210517_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admi',
            new_name='admiss',
        ),
    ]
